// Generated by tools/build-english.py; edit translation catalogues.
/* ====================================================================
   研究所 AI 手冊 — 單頁互動教學
   無外部依賴，file:// 直接開即可。
==================================================================== */

const $ = (sel, root = document) => root.querySelector(sel);
const $$ = (sel, root = document) => [...root.querySelectorAll(sel)];
const STORE_KEY = "ai-handbook-v3";

function loadStore() { try { return JSON.parse(localStorage.getItem(STORE_KEY) || "{}") || {}; } catch (e) { return {}; } }
function saveStore(patch) { try { localStorage.setItem(STORE_KEY, JSON.stringify({ ...loadStore(), ...patch })); } catch (e) { /* storage unavailable: keep working */ } }

/* ---------- 共用：複製 + toast ---------- */
function showToast(msg) {
  const t = $("#toast");
  t.textContent = msg;
  t.classList.add("show");
  clearTimeout(showToast._timer);
  showToast._timer = setTimeout(() => t.classList.remove("show"), 1600);
}

function copyText(text, btn) {
  const done = () => {
    showToast("Copied. Remember to adapt it to your material.");
    if (btn) {
      btn.classList.add("copied");
      const old = btn.textContent;
      btn.textContent = "Copied";
      setTimeout(() => { btn.classList.remove("copied"); btn.textContent = old; }, 1500);
    }
  };
  const fallback = () => {
    const active = document.activeElement;
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.style.position = "fixed";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.select();
    let copied = false;
    try { copied = document.execCommand("copy"); } catch (e) { /* use manual selection */ }
    ta.remove();
    if (active instanceof HTMLElement) active.focus({ preventScroll: true });
    if (copied) done();
    else {
      const panel = btn?.closest(".prompt-example, .builder-output, .pbox, .reading-source");
      const editor = panel?.querySelector("textarea");
      if (editor) { editor.focus({ preventScroll: true }); editor.select(); }
      showToast("Automatic copying failed. Select the text and copy it manually.");
    }
  };
  if (navigator.clipboard && window.isSecureContext) {
    navigator.clipboard.writeText(text).then(done).catch(fallback);
  } else fallback();
}

/* 文字框跟著內容長高，不要在小框裡捲動 */
function autoGrow(editor) {
  editor.style.height = "auto";
  editor.style.height = editor.scrollHeight + 2 + "px";
}

/* 把正文裡的填空位置 [像這樣] 標成不同顏色；括號內要有中文才算，[1] 這類引用編號不標；只包文字節點，複製出來的內容不變 */
function highlightPlaceholders(root = $("main")) {
  if (!root) return;
  const probe = /\[[^\[\]\n]*[A-Za-z][^\[\]\n]*\]/;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
    acceptNode: node => {
      const parent = node.parentElement;
      if (!parent || parent.closest("textarea, input, script, style, mark, .pbox.code")) return NodeFilter.FILTER_REJECT;
      return probe.test(node.nodeValue) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_SKIP;
    }
  });
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach(node => {
    const text = node.nodeValue, frag = document.createDocumentFragment(), re = /\[[^\[\]\n]*[A-Za-z][^\[\]\n]*\]/g;
    let last = 0, m;
    while ((m = re.exec(text))) {
      frag.append(text.slice(last, m.index));
      const mark = document.createElement("mark");
      mark.className = "placeholder";
      mark.textContent = m[0];
      frag.append(mark);
      last = m.index + m[0].length;
    }
    frag.append(text.slice(last));
    node.replaceWith(frag);
  });
}

/* 任何 data-copy-target="#id" 的按鈕都能複製對應元素的文字 */
function setupCopyTargets() {
  document.addEventListener("click", e => {
    const btn = e.target.closest("[data-copy-target]");
    if (!btn) return;
    const el = $(btn.dataset.copyTarget);
    if (el) copyText(el.innerText || el.textContent, btn);
  });
}

/* ====================================================================
   04 Prompt 組裝器(兩套公式)
==================================================================== */
const FORMULAS = [
  {
    label: "Understand something",
    hint: "Use this to understand something. Example: preparing for a postgraduate seminar.",
    empty: "(Start with the goal, then add information as needed.)",
    joiner: "\n",
    blocks: [
      { name: "Role", desc: "Who am I? What role should AI take?", text: "I am a postgraduate student. Answer as a helpful student in the year above.", on: false },
      { name: "Goal", desc: "What do I want to learn?", text: "Help me understand how to prepare for a postgraduate seminar.", on: true },
      { name: "Background", desc: "What does AI need to know about me?", text: "I am unfamiliar with seminar discussions and worried about speaking in English.", on: false },
      { name: "Constraints", desc: "What is in scope? What should it avoid?", text: "Focus on postgraduate classroom discussions. Use plain English and a natural tone.", on: false },
      { name: "Format", desc: "Bullets, a table or sections?", text: "Cover: 1. Preparation 2. Joining the discussion 3. Differences from undergraduate classes 4. Common difficulties 5. Where AI can help 6. Skills I need to practise myself.", on: false },
      { name: "Verification", desc: "What uncertainties should it flag?", text: "Mark anything that may vary between universities as 'check locally'. I will confirm the actual course and university requirements.", on: false }
    ]
  },
  {
    label: "Create something",
    hint: "Use this to create an output. Example: a self-introduction for induction.",
    empty: "(Start with the desired result, then add materials and acceptance criteria.)",
    joiner: "\n\n",
    blocks: [
      { name: "Situation", desc: "Your circumstances and available material", text: "# Situation\nMy course starts next month. Everyone needs a one-minute self-introduction in English for induction.", on: false },
      { name: "Difficulty", desc: "Where are you stuck?", text: "# Difficulty\nMy draft sounds like a memorised textbook. It feels stiff when I read it, and I stumble over difficult words.", on: false },
      { name: "Desired result", desc: "What do you want to produce?", text: "# Desired result\nHelp me write a natural, conversational self-introduction in English.", on: true },
      { name: "Acceptance criteria", desc: "What would a successful result look like?", text: "# Acceptance criteria\n- Around 100–120 words; I will read it aloud and adjust the timing\n- Avoid words that are hard to pronounce\n- End with one memorable sentence", on: false },
      { name: "Approach", desc: "How should it work with you?", text: "# Approach\nOffer three openings (humorous, sincere and concise). Let me choose before writing the full version.", on: false },
      { name: "Sample material", desc: "Provide your information or examples", text: "# Sample material\nExample person: Chen, from Taiwan, enjoys walking and photography, about to start postgraduate study. Replace this with my own details.", on: false }
    ]
  }
];

function renderBuilder() {
  const tabsBox = $("#formulaTabs");
  const hintBox = $("#formulaHint");
  const box = $("#builderBlocks");
  const result = $("#builderResult");
  let cur = 0;
  const stripHeading = text => text.replace(/^# [^\n]+\n/, "");
  const defaults = FORMULAS.map(f => f.blocks.map(b => b.on));
  const drafts = FORMULAS.map(f => f.blocks.map(b => stripHeading(b.text)));
  function copyContent() {
    const f = FORMULAS[cur];
    return f.blocks.flatMap((b, i) => {
      const value = drafts[cur][i];
      if (!b.on || !value.trim()) return [];
      const heading = b.text.match(/^# [^\n]+\n/);
      return [(heading ? heading[0] : "") + value];
    }).join(f.joiner);
  }
  const fitEditor = autoGrow;
  function compose() {
    const f = FORMULAS[cur];
    const lines = f.blocks.filter(b => b.on).map(b => b.text);
    if (lines.length === 0) { result.innerHTML = `<span class="placeholder">${f.empty}</span>`; return ""; }
    const text = lines.join(f.joiner);
    result.replaceChildren();
    f.blocks.forEach((b, i) => {
      if (!b.on) return;
      const part = document.createElement("span");
      part.className = "prompt-part";
      part.dataset.i = String(i);
      const label = document.createElement("label");
      label.className = "prompt-label";
      label.textContent = b.name;
      const body = document.createElement("textarea");
      body.className = "prompt-text";
      body.id = `prompt-edit-${cur}-${i}`;
      label.htmlFor = body.id;
      body.rows = 1;
      body.value = drafts[cur][i];
      body.placeholder = "Enter your text here";
      body.addEventListener("input", () => {
        drafts[cur][i] = body.value;
        fitEditor(body);
      });
      part.append(label, body);
      result.append(part);
      fitEditor(body);
    });
    return text;
  }
  function renderBlocks() {
    const f = FORMULAS[cur];
    hintBox.textContent = f.hint;
    box.innerHTML = f.blocks.map((b, i) => `<button class="block-btn${b.on ? " on" : ""}" type="button" data-i="${i}" aria-pressed="${b.on}"><span class="block-name">${b.name}</span><span class="block-desc">${b.desc}</span></button>`).join("");
    compose();
  }
  tabsBox.innerHTML = FORMULAS.map((f, i) => `<button class="formula-tab${i === 0 ? " active" : ""}" type="button" data-i="${i}" aria-pressed="${i === 0}">${f.label}</button>`).join("");
  const builderEl = $(".builder");
  tabsBox.addEventListener("click", e => { const btn = e.target.closest(".formula-tab"); if (!btn) return; cur = +btn.dataset.i; if (builderEl) builderEl.dataset.formula = String(cur); $$(".formula-tab", tabsBox).forEach(t => { t.classList.toggle("active", t === btn); t.setAttribute("aria-pressed", String(t === btn)); }); renderBlocks(); });
  if (builderEl) builderEl.dataset.formula = "0";
  box.addEventListener("click", e => { const btn = e.target.closest(".block-btn"); if (!btn) return; const b = FORMULAS[cur].blocks[+btn.dataset.i]; b.on = !b.on; btn.classList.toggle("on", b.on); btn.setAttribute("aria-pressed", String(b.on)); compose(); });
  $("#builderCopy").addEventListener("click", e => { const text = copyContent(); if (!text) { showToast("Select a block and enter some text first."); return; } copyText(text, e.currentTarget); });
  $("#builderReset").addEventListener("click", () => {
    FORMULAS[cur].blocks.forEach((b, i) => { b.on = defaults[cur][i]; });
    drafts[cur] = FORMULAS[cur].blocks.map(b => stripHeading(b.text));
    renderBlocks();
    showToast("Example restored.");
  });
  renderBlocks();
  window.handbookBuilder = {
    snapshot: () => ({ cur, drafts, selected: FORMULAS.map(f => f.blocks.map(b => b.on)) }),
    restore: state => {
      if (!state || !Array.isArray(state.drafts) || !Array.isArray(state.selected)) return;
      FORMULAS.forEach((f, fi) => f.blocks.forEach((b, bi) => {
        b.on = Boolean(state.selected[fi]?.[bi]);
        if (typeof state.drafts[fi]?.[bi] === "string") drafts[fi][bi] = state.drafts[fi][bi];
      }));
      tabsBox.querySelector(`[data-i="${state.cur === 1 ? 1 : 0}"]`).click();
    }
  };
  new ResizeObserver(() => $$("textarea", result).forEach(fitEditor)).observe(result);
}

/* ====================================================================
   06 Agent：示意步驟 + 這個月用哪個
==================================================================== */
const AGENT_STEPS = [
  { who: "ai", text: "Read the three documents", note: "Find requirements and deadlines, record filenames and page numbers, and list unreadable pages." },
  { who: "ai", text: "Organise and flag conflicts", note: "One report is due on 18 October on page 2, but 20 October on page 5. Flag it for confirmation." },
  { who: "you", text: "Supply the missing information", note: "Provide the lecturer's updated announcement confirming the deadline is 20 October." },
  { who: "ai", text: "Create and check the table", note: "Update the date, record the announcement source, sort by date, check for omissions and save a new assignments.csv." },
  { who: "you", text: "Open and verify the result", note: "Check deadlines against the documents and announcement before planning your work." }
];

function renderAgent() {
  const box = $("#agentSteps");
  let pos = 0;
  box.innerHTML = AGENT_STEPS.map((s, i) => `<div class="agent-step future" data-i="${i}"><span class="who ${s.who}">${s.who === "you" ? "You" : "AI"}</span><span><strong>${s.text}</strong><span class="step-note">${s.note}</span></span></div>`).join("");
  const steps = $$(".agent-step", box);
  const nextBtn = $("#agentNext");
  function update() {
    steps.forEach((el, i) => { el.classList.toggle("future", i > pos); el.classList.toggle("now", i === pos); });
    nextBtn.textContent = pos >= AGENT_STEPS.length - 1 ? "Done" : "Next step";
    nextBtn.disabled = pos >= AGENT_STEPS.length - 1;
  }
  nextBtn.addEventListener("click", () => { if (pos < AGENT_STEPS.length - 1) { pos++; update(); } });
  $("#agentReset").addEventListener("click", () => { pos = 0; update(); });
  update();
}


/* ====================================================================
   05 延伸：PDF.js + Citation.js 原始來源查證。只在展開時按需載入。
==================================================================== */
function setupEvidencePdfLab() {
  const lab = $("#pdfEvidenceLab");
  const viewer = $("#evidencePdfViewer");
  const canvas = $("#evidencePdfCanvas");
  const message = $("#evidencePdfMessage");
  const status = $("#evidencePdfStatus");
  const pageButtons = Array.from(document.querySelectorAll("#pdfEvidenceLab [data-evidence-page]"));
  if (!lab || !viewer || !canvas || !message || !status || !pageButtons.length) return;

  const source = {
    id: "lin-carter-2026",
    type: "report",
    title: "Evening Library Hours Pilot: A Teaching Brief",
    author: [
      { given: "Mei", family: "Lin" },
      { given: "James", family: "Carter" }
    ],
    issued: { "date-parts": [[2026]] },
    publisher: "Urban Learning Methods Lab"
  };
  let pdfDoc = null;
  let pdfJs = null;
  let currentPage = 2;
  let renderToken = 0;
  let loadingPdf = null;

  async function ensurePdf() {
    if (pdfDoc) return pdfDoc;
    if (loadingPdf) return loadingPdf;
    loadingPdf = (async () => {
      pdfJs = await import("./vendor/pdfjs/pdf.min.mjs");
      pdfJs.GlobalWorkerOptions.workerSrc = new URL("./vendor/pdfjs/pdf.worker.min.mjs", document.baseURI).href;
      const task = pdfJs.getDocument({ url: "./materials/evidence-library-pilot.pdf" });
      pdfDoc = await task.promise;
      return pdfDoc;
    })();
    return loadingPdf;
  }

  async function renderPage(pageNumber) {
    currentPage = pageNumber;
    pageButtons.forEach(btn => btn.setAttribute("aria-pressed", String(Number(btn.dataset.evidencePage) === pageNumber)));
    viewer.setAttribute("aria-busy", "true");
    message.hidden = false;
    message.textContent = "Loading the original PDF…";
    const token = ++renderToken;
    try {
      const doc = await ensurePdf();
      const page = await doc.getPage(pageNumber);
      if (token !== renderToken) return;
      const baseViewport = page.getViewport({ scale: 1 });
      const available = Math.max(520, Math.min(720, (viewer.clientWidth || 680) - 24));
      const scale = available / baseViewport.width;
      const viewport = page.getViewport({ scale });
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      canvas.width = Math.floor(viewport.width * dpr);
      canvas.height = Math.floor(viewport.height * dpr);
      canvas.style.width = viewport.width + "px";
      canvas.style.height = viewport.height + "px";
      const context = canvas.getContext("2d", { alpha: false });
      await page.render({ canvasContext: context, viewport, transform: dpr === 1 ? null : [dpr, 0, 0, dpr, 0, 0] }).promise;
      if (token !== renderToken) return;
      canvas.setAttribute("aria-label", "Fictional teaching PDF, page " + pageNumber + " of " + doc.numPages + " pages");
      status.textContent = "Original PDF: page " + pageNumber + " / " + doc.numPages;
      message.hidden = true;
    } catch (error) {
      canvas.width = 0;
      canvas.height = 0;
      status.textContent = "Interactive PDF unavailable";
      message.hidden = false;
      message.innerHTML = 'PDF.js could not load here. Use \'Open PDF directly\' above to read the original.';
    } finally {
      viewer.setAttribute("aria-busy", "false");
    }
  }

  lab.addEventListener("toggle", () => {
    if (!lab.open) return;
    renderPage(currentPage);
  });
  pageButtons.forEach(btn => btn.addEventListener("click", () => renderPage(Number(btn.dataset.evidencePage))));
  window.addEventListener("resize", () => { if (lab.open && pdfDoc) renderPage(currentPage); });
}

/* ====================================================================
   06 延伸：Observable Plot 小實驗。只在使用者展開相應練習時載入本地 vendor。
==================================================================== */
let observablePlotLoading = null;

function loadVendorScript(src, marker) {
  return new Promise((resolve, reject) => {
    const existing = document.querySelector('script[' + marker + ']');
    if (existing) {
      if (existing.dataset.loaded === "true") resolve();
      else {
        existing.addEventListener("load", () => resolve(), { once: true });
        existing.addEventListener("error", () => reject(new Error(src + " failed to load")), { once: true });
      }
      return;
    }
    const script = document.createElement("script");
    script.src = src;
    script.setAttribute(marker, "true");
    script.onload = () => { script.dataset.loaded = "true"; resolve(); };
    script.onerror = () => reject(new Error(src + " failed to load"));
    document.head.append(script);
  });
}

function loadObservablePlot() {
  if (window.Plot && window.d3) return Promise.resolve(window.Plot);
  if (observablePlotLoading) return observablePlotLoading;
  observablePlotLoading = (async () => {
    if (!window.d3) await loadVendorScript("./vendor/d3.min.js", "data-d3-vendor");
    if (!window.Plot) await loadVendorScript("./vendor/observable-plot.umd.min.js", "data-observable-plot");
    if (!window.Plot) throw new Error("Plot global missing");
    return window.Plot;
  })();
  return observablePlotLoading;
}

function setupUnitConversionPlot() {
  const lesson = $("#lesson-units");
  const chart = $("#unitsPlot");
  const takeaway = $("#unitsPlotTakeaway");
  const buttons = Array.from(document.querySelectorAll("#unitsPlotLab [data-unit-mode]"));
  if (!lesson || !chart || !takeaway || !buttons.length) return;

  const data = [
    { id: "D1", name: "D1 Riverside", raw: 1200, unit: "month", monthly: 1200 },
    { id: "D2", name: "D2 Old Town", raw: 280, unit: "week", monthly: 1213.33 }
  ];
  let mode = "raw";
  let plotApi = null;

  function money(value) {
    return value.toLocaleString("en-GB", { minimumFractionDigits: Number.isInteger(value) ? 0 : 2, maximumFractionDigits: 2 });
  }

  function render() {
    if (!plotApi) return;
    const styles = getComputedStyle(document.documentElement);
    const brand = styles.getPropertyValue("--brand").trim() || "#1B5E73";
    const warning = styles.getPropertyValue("--terracotta").trim() || "#9E3F2E";
    const rows = data.map(d => ({
      ...d,
      value: mode === "monthly" ? d.monthly : d.raw,
      label: mode === "monthly" ? "£" + money(d.monthly) + "/month" : "£" + money(d.raw) + "/" + d.unit
    }));

    if (mode === "raw") {
      takeaway.innerHTML = "<strong>Not directly comparable.</strong> 280 is weekly; 1,200 is monthly. The apparent difference is caused by different units.";
    } else {
      takeaway.innerHTML = "<strong>Compare the same units.</strong> D2 is about £1,213.33/month, around £13.33 more than D1 at £1,200/month.";
    }

    // 寬度跟著實際版面；窄螢幕縮小邊界與字級，軸說明改短句。
    const width = Math.max(260, Math.min(860, (chart.clientWidth || 656) - 16));
    const narrow = width < 560;
    const phone = window.innerWidth <= 700;
    const fontPx = phone ? 14 : 16;
    const marginLeft = phone ? 92 : 118, marginRight = 24;
    const plotWidth = width - marginLeft - marginRight;
    // 長條太短放不下金額時，金額改放在長條右邊，避免壓到區名。
    const fitsInside = d => d.value / 1300 * plotWidth > d.label.length * fontPx * 0.62 + 16;
    const ink = styles.getPropertyValue("--ink-primary").trim() || "#1C2A2C";
    const axisLabel = mode === "raw" ? (narrow ? "Raw values (different units)" : "Raw values (different units; not comparable)") : "Monthly rent (GBP)";
    const plot = plotApi.plot({
      width,
      height: 262,
      marginLeft,
      marginRight,
      marginBottom: 64,
      x: { domain: [0, 1300], grid: true, label: axisLabel, labelAnchor: "center", labelArrow: "none", labelOffset: 52 },
      y: { domain: data.map(d => d.name), label: null },
      style: { fontFamily: "inherit", fontSize: fontPx + "px" },
      marks: [
        plotApi.ruleX([0]),
        plotApi.barX(rows, { x: "value", y: "name", fill: d => mode === "raw" && d.id === "D2" ? warning : brand, title: d => d.name + ": " + d.label }),
        plotApi.text(rows.filter(fitsInside), { x: "value", y: "name", text: "label", textAnchor: "end", dx: -8, fill: "white", fontWeight: 700 }),
        plotApi.text(rows.filter(d => !fitsInside(d)), { x: "value", y: "name", text: "label", textAnchor: "start", dx: 8, fill: ink, fontWeight: 700 })
      ]
    });
    plot.setAttribute("role", "img");
    plot.setAttribute("aria-label", mode === "raw" ? "Incorrect example: D1's 1,200 per month and D2's 280 per week are on the same scale. This cannot show which is cheaper." : "Rents in the same units: D1 is 1,200 per month; D2 is about 1,213.33 per month." );
    chart.replaceChildren(plot);
  }

  async function ensurePlot() {
    if (plotApi) { render(); return; }
    chart.innerHTML = '<p class=\"plot-loading\">Loading interactive chart…</p>';
    try {
      plotApi = await loadObservablePlot();
      render();
    } catch (error) {
      chart.innerHTML = '<p class=\"plot-loading\"><strong>Chart unavailable.</strong> The key point remains: convert to the same time unit before comparing.</p>';
    }
  }

  lesson.addEventListener("toggle", () => { if (lesson.open) ensurePlot(); });
  buttons.forEach(btn => btn.addEventListener("click", () => {
    mode = btn.dataset.unitMode;
    buttons.forEach(other => other.setAttribute("aria-pressed", String(other === btn)));
    ensurePlot();
  }));
  if (lesson.open) ensurePlot();
}

/* ====================================================================
   06 延伸：缺值互動圖。Observable Plot 僅在使用者展開本題時從本地 vendor 載入。
==================================================================== */
function setupMissingValuePlot() {
  const lesson = $("#lesson-missing");
  const chart = $("#missingPlot");
  const takeaway = $("#missingPlotTakeaway");
  const buttons = Array.from(document.querySelectorAll("#missingPlotLab [data-missing-mode]"));
  if (!lesson || !chart || !takeaway || !buttons.length) return;

  const data = [
    { id: "D1", name: "Riverside", rent: 1200 },
    { id: "D2", name: "Old Town", rent: 1213.33 },
    { id: "D3", name: "University", rent: 950 },
    { id: "D4", name: "Industrial", rent: null },
    { id: "D5", name: "New Town", rent: 910 },
    { id: "D6", name: "Station", rent: 1450 }
  ];
  let mode = "missing";
  let plotApi = null;

  function render() {
    if (!plotApi) return;
    const styles = getComputedStyle(document.documentElement);
    const brand = styles.getPropertyValue("--brand").trim() || "#1B5E73";
    const warning = styles.getPropertyValue("--terracotta").trim() || "#9E3F2E";
    const rows = data.map(d => ({ ...d, value: d.rent == null && mode === "zero" ? 0 : d.rent }));
    const numeric = rows.filter(d => Number.isFinite(d.value));
    const d4 = rows.find(d => d.id === "D4");
    const marks = [
      plotApi.ruleX([0]),
      plotApi.barX(numeric, { x: "value", y: "name", fill: d => d.id === "D4" ? warning : brand, title: d => d.value == null ? "No data" : d.id + " " + d.name + ": £" + d.value.toLocaleString("en-GB", { maximumFractionDigits: 2 }) + "/month" })
    ];

    if (mode === "missing") {
      marks.push(plotApi.text([{ name: d4.name, value: 0, label: "No data" }], { x: "value", y: "name", text: "label", textAnchor: "start", dx: 7, fill: warning, fontWeight: 700 }));
      takeaway.innerHTML = "<strong>No data ≠ 0.</strong> D4 has no observed rent, so it cannot be ranked as the cheapest district.";
    } else {
      marks.push(plotApi.dot([{ name: d4.name, value: 0 }], { x: "value", y: "name", r: 5, fill: warning }));
      marks.push(plotApi.text([{ name: d4.name, value: 0, label: "£0 (wrong)" }], { x: "value", y: "name", text: "label", textAnchor: "start", dx: 9, fill: warning, fontWeight: 700 }));
      takeaway.innerHTML = "<strong>Incorrect example:</strong> replacing the blank with 0 makes D4 look like an observed £0 rent and, wrongly, the cheapest district.";
    }

    const width = Math.max(260, Math.min(860, (chart.clientWidth || 656) - 16));
    const phone = window.innerWidth <= 700;
    const plot = plotApi.plot({
      width,
      height: 316,
      marginLeft: phone ? 92 : 118,
      marginRight: 24,
      marginBottom: 64,
      x: { domain: [0, 1550], grid: true, label: "Monthly rent (GBP)", labelAnchor: "center", labelArrow: "none", labelOffset: 52 },
      y: { domain: data.map(d => d.name), label: null },
      style: { fontFamily: "inherit", fontSize: (phone ? 14 : 16) + "px" },
      marks
    });
    plot.setAttribute("role", "img");
    plot.setAttribute("aria-label", mode === "missing" ? "Rent comparison: D4 shows No data and is excluded from the ranking." : "Incorrect rent comparison: D4's missing value has been replaced with zero." );
    chart.replaceChildren(plot);
  }

  async function ensurePlot() {
    if (plotApi) { render(); return; }
    chart.innerHTML = '<p class=\"plot-loading\">Loading interactive chart…</p>';
    try {
      plotApi = await loadObservablePlot();
      render();
    } catch (error) {
      chart.innerHTML = '<p class=\"plot-loading\"><strong>Chart unavailable.</strong> The key point remains: D4 is unknown and must not be changed to £0.</p>';
    }
  }

  lesson.addEventListener("toggle", () => { if (lesson.open) ensurePlot(); });
  buttons.forEach(btn => btn.addEventListener("click", () => {
    mode = btn.dataset.missingMode;
    buttons.forEach(other => other.setAttribute("aria-pressed", String(other === btn)));
    ensurePlot();
  }));
  if (lesson.open) ensurePlot();
}

/* ====================================================================
   07 圖表：分頁即決策表，一次看一張
==================================================================== */
function renderDiagrams() {
  const list = window.DIAGRAMS || [];
  const tabs = $("#diagramTabs");
  if (!tabs || !list.length) return;
  tabs.innerHTML = list.map((d, i) => `<button type="button" class="diagram-tab${i ? "" : " active"}" id="diagram-tab-${d.id}" aria-controls="diagramPanel" role="tab" tabindex="${i ? -1 : 0}" aria-selected="${i ? "false" : "true"}" data-diagram="${d.id}"><b>${d.name}</b><span>${d.when}</span></button>`).join("");
  function show(id) {
    const d = list.find(x => x.id === id);
    if (!d) return;
    $("#diagramImg").src = `diagrams/en/${d.id}.svg`;
    $("#diagramImg").alt = `${d.name} example`;
    $("#diagramCaption").innerHTML = `<strong>${d.name}</strong> · Example: ${d.example}`;
    $("#diagramSay").textContent = d.say;
    $("#diagramTweak").textContent = `Try adjusting: ${d.tweak}`;
    $("#diagramCode").textContent = d.code;
    $("#diagramPanel").setAttribute("aria-labelledby", `diagram-tab-${d.id}`);
    $$(".diagram-tab", tabs).forEach(t => { const on = t.dataset.diagram === id; t.classList.toggle("active", on); t.setAttribute("aria-selected", String(on)); t.tabIndex = on ? 0 : -1; });
  }
  tabs.addEventListener("click", e => { const btn = e.target.closest(".diagram-tab"); if (btn) show(btn.dataset.diagram); });
  tabs.addEventListener("keydown", e => {
    const buttons = $$(".diagram-tab", tabs), index = buttons.indexOf(document.activeElement);
    if (index < 0 || !["ArrowRight", "ArrowLeft", "Home", "End"].includes(e.key)) return;
    e.preventDefault();
    const next = e.key === "Home" ? 0 : e.key === "End" ? buttons.length - 1 : (index + (e.key === "ArrowRight" ? 1 : -1) + buttons.length) % buttons.length;
    show(buttons[next].dataset.diagram); buttons[next].focus({ preventScroll: true });
    buttons[next].scrollIntoView({ block: "nearest", inline: "nearest", behavior: "instant" });
  });
  const dialog = $("#diagramZoom"), scaleBtn = $("#diagramZoomScale");
  const setScale = actual => {
    dialog.classList.toggle("actual", actual);
    scaleBtn.setAttribute("aria-pressed", String(actual));
    scaleBtn.textContent = actual ? "Fit diagram" : "Actual size";
  };
  scaleBtn.addEventListener("click", () => setScale(!dialog.classList.contains("actual")));
  const openZoom = source => {
    const large = $("#diagramZoomImg");
    large.src = source.currentSrc || source.src; large.alt = source.alt;
    $("#diagramZoomTitle").textContent = source.alt;
    dialog.classList.toggle("shot", Boolean(source.closest(".form-shot")));
    setScale(false);
    dialog.showModal();
  };
  $("#diagramZoomOpen").addEventListener("click", () => openZoom($("#diagramImg")));
  // 06 章五種形態的示意圖在手機上很小：點圖(或按 Enter)用同一個檢視窗放大
  $$(".form-shot img").forEach(img => {
    img.tabIndex = 0;
    img.setAttribute("role", "button");
    img.addEventListener("click", () => openZoom(img));
    img.addEventListener("keydown", e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); openZoom(img); } });
  });
  $("#diagramZoomClose").addEventListener("click", () => dialog.close());
  dialog.addEventListener("click", e => { if (e.target === dialog) dialog.close(); });
  show(list[0].id);
}

/* ====================================================================
   08 規則清單：勾選保存在瀏覽器
==================================================================== */
function setupChecklist() {
  const boxes = $$("#rulesChecklist input[data-rule]");
  if (!boxes.length) return;
  const done = new Set(loadStore().rules || []);
  boxes.forEach(cb => {
    cb.checked = done.has(cb.dataset.rule);
    cb.addEventListener("change", () => { if (cb.checked) done.add(cb.dataset.rule); else done.delete(cb.dataset.rule); saveStore({ rules: [...done] }); });
  });
  const reset = $("#rulesReset");
  if (reset) reset.addEventListener("click", () => {
    boxes.forEach(cb => { cb.checked = false; });
    done.clear();
    saveStore({ rules: [] });
    showToast("Checks cleared. Review them again for each assignment.");
  });
}

/* ====================================================================
   09 提示詞庫
==================================================================== */
const PROMPT_CARDS = [
  {
    "title": "Build a source library with Deep Research",
    "when": "Gemini Notebook",
    "where": "Paste this into the Add sources search box in the Sources panel on the left, choose Web and Deep Research, then send. Do not paste it into the chat box in the middle. When the results arrive, check which sources it found, add only credible ones to the notebook, then use the examples below.",
    "text": "I want to research [topic]. First build a research framework: identify the core question and key sub-questions, and do not draw conclusions yet. Then search for credible sources, prioritising primary sources and adding high-quality secondary sources. Once the source library is built, compare the sources for agreement, disagreement, contradictions and gaps, and state which points are well supported by evidence, which remain contested and which need further checking. If the information is insufficient, say so clearly instead of filling the gaps with speculation."
  },
  {
    "title": "Understand and verify a reading",
    "when": "Gemini Notebook",
    "text": "Using only my article, explain the main question, the author's claims and the limitations in plain English, with citations.\nI am struggling with [passage or question]. Explain this part; clearly label any invented examples. Separate the source's content from your inferences."
  },
  {
    "title": "Compare several readings",
    "when": "Gemini Notebook",
    "text": "Using only my sources, compare their claims, evidence and limitations about [research question], with citations I can follow.\nIdentify agreement and disagreement. Write 'not provided' where information is missing; do not guess."
  },
  {
    "title": "Find relevant passages",
    "when": "Gemini Notebook",
    "text": "Find passages related to [concept or question]. Cite each and briefly explain its relevance.\nPreserve differences between sources rather than merging them into one conclusion. Say if nothing is found; I will also search the original text for relevant keywords."
  },
  {
    "title": "Organise a lecture recording",
    "when": "Gemini Notebook",
    "text": "I have permission to record and upload this audio. Using only the recording, summarise the main topics and explicitly stated assignment requirements, with references I can use to listen again.\nFlag unclear names, terms, figures and dates. Do not guess."
  },
  {
    "title": "Create an audio overview",
    "when": "Gemini Notebook",
    "text": "Audience: a postgraduate new to this topic.\nFocus: [question I want to understand]. Compare the sources' main views and limitations.\nLevel: keep important technical terms and explain each simply on first use.\nLength: brief; avoid repeating background or adding facts absent from the sources."
  },
  {
    "title": "Create an infographic or slides",
    "when": "Gemini Notebook",
    "text": "Using the selected sources, create [a one-page infographic / slides] for [audience].\nFocus on [what readers should understand]. Present the main findings and limitations, using only numbers in the sources.\nKeep one main point per page or section, and retain important conditions and source details."
  },
  {
    "title": "Turn a video into an infographic",
    "when": "Other useful prompts",
    "text": "Generate a detailed infographic diagram\nBased on this video, create a detailed infographic.\n\n(Paste the video link here — an open course or educational video is fine.)\n\nTop header: Use 5% of the total height for a full-width technology-blue (#0052CC) bar, with the title in lightning gold (#FFD700) and an extra-bold font.\n\nChoose the visual elements you think are appropriate. Make the content as rich as possible, aiming to cover more than 95% of the video's key points.\nUse English for the text, retaining technical terms in their original language.\n\nUse a light grey-white background. Make good use of the available space, establish a clear visual hierarchy, and use contrasting, analogous or monochromatic colours, or different typefaces, to emphasise key points. Keep the text as large as possible so readers can identify all the main points at a glance."
  },
  {
    "title": "Review a draft's argument and evidence",
    "when": "Other useful prompts",
    "text": "Review my draft. Restate its main argument, then identify up to three priorities for revision, such as weak evidence, a leap in reasoning or an unclear concept.\nQuote specific sentences and explain the problem and direction for revision. Do not rewrite it yet or invent supporting evidence.\n\nAssignment requirements: [paste]\nDraft: [paste]"
  },
  {
    "title": "Practise a seminar discussion",
    "when": "Other useful prompts",
    "text": "I will discuss [topic]. My view is [view]. Act as a classmate who asks thoughtful follow-up questions. Ask one question at a time and wait for my answer.\nFocus on content first; offer brief language advice if needed. Flag weak evidence without inventing support for me."
  },
  {
    "title": "Organise requirements and deadlines",
    "when": "Other useful prompts",
    "text": "Using my course documents, make a table of assignments: course, assignment name, required submission, deadline date and time, source filename and page.\nMark missing details 'not provided'. Show conflicting information side by side without choosing for me. I will check the originals.\nIf saving a file, create a new one without modifying the source material."
  }
];
const CARD_GROUPS = [
  { when: "Gemini Notebook", name: "Gemini Notebook", tool: "Read and organise sources" },
  { when: "Other useful prompts", name: "Other useful prompts", tool: "Conversational AI; use an Agent for local file tasks" }
];

function renderCards() {
  const lib = $("#cardLib");
  lib.replaceChildren();
  CARD_GROUPS.forEach(group => {
    const section = document.createElement("div");
    section.className = "prompt-example-group";
    const heading = document.createElement("h3");
    heading.textContent = group.name;
    const note = document.createElement("p");
    note.className = "prompt-group-note";
    note.textContent = group.tool;
    section.append(heading, note);
    lib.append(section);
    PROMPT_CARDS.forEach((card, i) => {
    if (card.when !== group.when) return;
    const details = document.createElement("details");
    details.className = "prompt-example";
    const summary = document.createElement("summary");
    summary.textContent = card.title;
    const editor = document.createElement("textarea");
    editor.id = `saved-prompt-${i}`;
    editor.value = card.text;
    editor.rows = 3; // 展開後會自動長高到內容高度；3 行只是最小高度，短提示詞不會留一大塊空白
    editor.setAttribute("aria-label", `${card.title}: editable prompt`);
    const copy = document.createElement("button");
    copy.type = "button";
    copy.className = "copy-btn primary";
    copy.textContent = "Copy";
    copy.addEventListener("click", () => {
      if (!editor.value.trim()) { showToast("Enter some text first."); return; }
      copyText(editor.value, copy);
    });
    const reset = document.createElement("button");
    reset.type = "button";
    reset.className = "copy-btn";
    reset.textContent = "Reset example";
    reset.addEventListener("click", () => { editor.value = card.text; autoGrow(editor); showToast("Example restored."); });
    editor.addEventListener("input", () => autoGrow(editor));
    details.addEventListener("toggle", () => { if (details.open) autoGrow(editor); });
    // 提示詞放在深色框裡(全站可複製的提示詞都是深色框)，框頂寫明「提示詞」，複製按鈕貼著它
    const label = Object.assign(document.createElement("label"), { htmlFor: editor.id, className: "prompt-box-label", textContent: "Prompt" });
    const hasSlots = /\[[^\[\]\n]*[A-Za-z][^\[\]\n]*\]/.test(card.text);
    const hint = Object.assign(document.createElement("span"), { className: "prompt-box-hint", textContent: hasSlots ? "Replace the [ ] parts, then copy" : "Edit it if needed, then copy" });
    const actions = Object.assign(document.createElement("div"), { className: "prompt-box-actions" });
    actions.append(reset, copy);
    const head = Object.assign(document.createElement("div"), { className: "prompt-box-head" });
    head.append(label, hint, actions);
    const box = Object.assign(document.createElement("div"), { className: "prompt-box" });
    box.append(head, editor);
    // 選填：這張提示詞不是貼在對話框時，先在框外說清楚怎麼用
    let where = null;
    if (card.where) {
      where = Object.assign(document.createElement("div"), { className: "prompt-where" });
      where.append(Object.assign(document.createElement("strong"), { textContent: "How to use" }), Object.assign(document.createElement("p"), { textContent: card.where }));
    }
    details.append(summary, ...(where ? [where] : []), box);
    section.append(details);
    });
  });
  window.addEventListener("resize", () => $$(".prompt-example[open] textarea").forEach(autoGrow));
}

/* ====================================================================
   手機介面：目錄選單、目前章節、表格變卡片、短片點一下播放
==================================================================== */
function setupManifest() {
  if (!/^https?:$/.test(location.protocol)) return;
  const link = document.createElement("link"); link.rel = "manifest"; link.href = "./manifest.webmanifest"; document.head.appendChild(link);
}

function setupMobileMenu() {
  const btn = $("#menuBtn"), nav = $("#topnav"), main = $("main"), now = $("#navNow");
  if (!btn || !nav) return;
  if (now && !now.textContent) now.textContent = "Graduate AI Handbook";
  const compact = window.matchMedia("(max-width: 1260px)");
  const setBarHeight = () => document.documentElement.style.setProperty("--bar-h", $(".topbar").offsetHeight + "px");
  const open = (on, returnFocus = false) => {
    document.body.classList.toggle("menu-open", on);
    btn.setAttribute("aria-expanded", String(on));
    btn.textContent = on ? "Close" : "Menu";
    main.inert = on;
    if (on) (nav.querySelector(".active") || nav.querySelector("a")).focus();
    else if (returnFocus) btn.focus();
  };
  setBarHeight();
  window.addEventListener("resize", () => {
    if (!compact.matches) open(false);
    setBarHeight();
  });
  btn.addEventListener("click", () => open(!document.body.classList.contains("menu-open")));
  nav.addEventListener("click", e => {
    const link = e.target.closest("a");
    if (!link || !compact.matches) return;
    open(false);
    const target = $(link.getAttribute("href"));
    target.setAttribute("tabindex", "-1");
    target.focus({ preventScroll: true });
  });
  document.addEventListener("keydown", e => {
    if (!document.body.classList.contains("menu-open")) return;
    if (e.key === "Escape") { e.preventDefault(); open(false, true); }
    if (e.key !== "Tab") return;
    const last = nav.querySelector("a:last-child");
    if (e.shiftKey && document.activeElement === btn) { e.preventDefault(); last.focus(); }
    else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); btn.focus(); }
  });
}

function labelTables() {
  $$("table.reading-table").forEach(t => {
    const heads = $$("thead th", t).map(th => th.textContent.trim());
    $$("tbody tr", t).forEach(tr => [...tr.children].forEach((td, i) => { if (heads[i]) td.dataset.label = heads[i]; }));
  });
}

function setupClips() {
  const videos = $$(".clip video");
  $$(".keyword-example, .learning-lesson").forEach(details => {
    const video = details.querySelector("video");
    if (!video) return;
    details.addEventListener("toggle", () => {
      if (!details.open) video.pause();
    });
  });
  videos.forEach(video => video.addEventListener("play", () => {
    videos.forEach(other => { if (other !== video) other.pause(); });
  }));
  document.addEventListener("visibilitychange", () => {
    if (document.hidden) videos.forEach(video => video.pause());
  });
}

/* ====================================================================
   導覽列高亮 + 舊網址相容
==================================================================== */
function setupNav() {
  const links = $$("#topnav a"), now = $("#navNow");
  const sections = links.map(a => $(a.getAttribute("href")));
  let pending = false;
  const update = () => {
    pending = false;
    // 章節標題捲過畫面上方約三成就算進入該章(只用頂欄下 32px 時，標題已在眼前卻還顯示上一章)
    const threshold = $(".topbar").getBoundingClientRect().height + Math.min(window.innerHeight * 0.3, 260);
    let current = -1;
    sections.forEach((section, i) => { if (section.getBoundingClientRect().top <= threshold) current = i; });
    if (window.scrollY > 0 && window.innerHeight + window.scrollY >= document.documentElement.scrollHeight - 8) current = sections.length - 1;
    links.forEach((link, i) => {
      link.classList.toggle("active", i === current);
      if (i === current) link.setAttribute("aria-current", "location");
      else link.removeAttribute("aria-current");
    });
    if (now) now.textContent = current < 0 ? "Graduate AI Handbook" : links[current].dataset.num + " " + links[current].textContent;
    // 手機頂欄：捲進章節後顯示目前章節，回到開場再顯示「AI 手冊」
    document.body.classList.toggle("in-chapter", current >= 0);
  };
  const schedule = () => { if (!pending) { pending = true; requestAnimationFrame(update); } };
  window.addEventListener("scroll", schedule, { passive: true });
  window.addEventListener("resize", schedule);
  window.addEventListener("hashchange", schedule);
  new ResizeObserver(schedule).observe($("main"));
  update();
}

function migrateOldRoutes() {
  const h = location.hash;
  if (!h || document.getElementById(h.slice(1))) return;
  const unitMap = { intro: "concepts", rules: "rules", gemini: "prompt", diagrams: "diagrams", notebooklm: "reading", agent: "agent", onward: "situations" };
  const [head, id] = h.slice(1).split("/");
  let target = "hero";
  if (head === "course" || head === "lesson") target = unitMap[id] || "concepts";
  else if (head === "situation" || head === "situations") target = "situations";
  else if (head === "glossary") target = "concepts";
  else if (head === "prompts") target = "cards";
  location.replace("#" + target);
}

/* Line breaks CSS cannot express. Product names such as Claude Code never split across lines,
   and "A / B" lists break after the slash, not before it. Chinese can break between any two
   characters and Chromium's text-wrap: pretty does not rebalance it, so the last words of each
   block (at least two words and three letters) stay together with the closing punctuation: no
   line holds a lone character and the final word is not split. Nothing is measured, so it holds
   at every width. Text that a button copies and hidden labels are left untouched. */
function keepPhrasesTogether() {
  const skip = ["pre", "code", "textarea", "svg", "script", "style", ".sr-only", "#builderResult", "#readingSource",
    ...[...document.querySelectorAll("[data-copy-target]")].map(btn => btn.dataset.copyTarget)].join(", ");
  const nbsp = String.fromCharCode(160);
  const names = /Claude Code|Gemini Notebook|VS Code|Deep Research/g;
  const display = new Map();
  const displayOf = el => {
    if (!display.has(el)) display.set(el, getComputedStyle(el).display);
    return display.get(el);
  };
  const lastText = new Map();
  const walker = document.createTreeWalker($("main"), NodeFilter.SHOW_TEXT);
  for (let node; (node = walker.nextNode());) {
    if (!node.data.trim() || node.parentElement.closest(skip)) continue;
    // The opening cards' titles are too narrow at laptop widths for an unbreakable "Gemini Notebook".
    if (!node.parentElement.closest(".hero-card strong, .hero-tool-options")) {
      node.data = node.data.replace(names, name => name.replace(" ", nbsp)).replace(/ \/ /g, nbsp + "/ ");
    }
    let block = node.parentElement;
    while (block && ["inline", "contents"].includes(displayOf(block))) block = block.parentElement;
    if (block) lastText.set(block, node);
  }
  if (!document.documentElement.lang.startsWith("zh") || !window.Intl?.Segmenter) return;
  const words = new Intl.Segmenter("zh-Hant", { granularity: "word" });
  const opening = new RegExp("[\\u300c\\u300e\\uff08(\\[]");
  const onlyClosing = new RegExp("^[\\s\\u3000-\\u303f\\uff00-\\uffef)\\]]{1,3}$");
  const glueEnding = node => {
    const parts = [...words.segment(node.data)];
    let start = -1, count = 0, letters = 0;
    for (let k = parts.length - 1; k >= 0 && (count < 2 || letters < 3); k--) {
      const part = parts[k];
      if (part.isWordLike) {
        if (node.data.length - part.index > 12) break;
        count += 1;
        letters += part.segment.length;
        start = part.index;
      } else if (count && opening.test(part.segment)) break;
    }
    if (!count) return false;
    const glue = document.createElement("keep-together");
    glue.textContent = node.data.slice(start);
    node.data = node.data.slice(0, start);
    node.after(glue);
    return true;
  };
  lastText.forEach(node => {
    // Directly inside a flex or grid container, a new element would become an item of its own.
    if (/flex|grid/.test(displayOf(node.parentElement)) || glueEnding(node)) return;
    // Only punctuation after a link or placeholder: punctuation never starts a line, so keeping
    // the end of that element's own text together is enough.
    const before = node.previousSibling;
    if (onlyClosing.test(node.data) && before?.nodeType === Node.ELEMENT_NODE) {
      const inner = [...before.childNodes].reverse().find(child => child.nodeType === Node.TEXT_NODE && child.data.trim());
      if (inner) glueEnding(inner);
    }
  });
}

/* ---------- 啟動 ---------- */
setupCopyTargets();
renderBuilder();
renderAgent();
setupEvidencePdfLab();
setupUnitConversionPlot();
setupMissingValuePlot();
renderDiagrams();
setupChecklist();
renderCards();
highlightPlaceholders();
setupNav();
setupManifest();
setupMobileMenu();
labelTables();
keepPhrasesTogether();
setupClips();
migrateOldRoutes();
window.addEventListener("hashchange", migrateOldRoutes);
$("#readingCopy").addEventListener("click", e => copyText($("#readingSource").innerText || $("#readingSource").textContent, e.currentTarget));
